CADASTRO_NOME_COMPLETO = "Qual o seu nome completo?"
CADASTRO_FUNCAO = "Qual a sua função no projeto?"
CADASTRO_COORDENADOR = "Quem é o professor responsável pelo seu projeto?"
CADASTRO_ID_STONELAB = "id_stonelab"
CADASTRO_NOME_ENTRADA = "nome_entrada"

IO_COL_ID_RAW = "ID_Stonelab"
IO_COL_START_RAW = "Quando a data de referência?"
IO_COL_FREQ1_RAW = "Frequência esperada"
IO_COL_END1_RAW = "end_date_1"
IO_COL_END2_RAW = "end_date_2"
IO_COL_FREQ2_RAW = "freq_2"

JUSTIFICATIVA_INICIO = "Início da ausência"
JUSTIFICATIVA_FIM = "Fim da ausência"
JUSTIFICATIVA_ID_STONELAB = "Qual seu ID StoneLab? (caso não saiba, procure nossa equipe)"
JUSTIFICATIVA_MOTIVO = "Motivo da ausência"
JUSTIFICATIVA_MOTIVO_FERIAS = "Férias"

FERIADOS_DATA = "Data"

COL_NAME = "name"
COL_FUNCTION = "function"
COL_COORDINATOR = "coordinator"
COL_ID_STONELAB = "id_stonelab"
COL_NOME_ENTRADA = "nome_entrada"
COL_DATE = "date"
COL_XML_DATE = "Date"
COL_START = "start"
COL_END = "end"
COL_REASON = "reason"

COL_IO_START = "start_date"
COL_IO_END1 = "end_date_1"
COL_IO_END2 = "end_date_2"
COL_IO_FREQ1 = "freq_1"
COL_IO_FREQ2 = "freq_2"

OUT_COL_NOME = "Nome"
OUT_COL_FUNCAO = "Função"
OUT_COL_COORDENADOR = "Coordenador"
OUT_COL_SEMANA = "Semana"
OUT_COL_FREQ_OBS = "Freq Obs"
OUT_COL_FREQ_ESP = "Freq Esp"
OUT_COL_DIAS_UTEIS = "Dias Úteis"
OUT_COL_FALTAS_JUST = "Falt Just"
OUT_COL_DIAS_FERIAS = "Dias de Férias"
OUT_COL_SITUACAO = "Situação de Atingimento"

OUT_COL_ACOES_NOME_XML = "nome_entrada"
OUT_COL_ACOES_SEMANA = "Semana"
OUT_COL_ACOES_FREQ_OBS = "Freq Obs"
OUT_COL_ACOES_SITUACAO = "Situacao"

STATUS_ATINGIU = "Atingiu"
STATUS_NAO_ATINGIU = "Não Atingiu"
STATUS_JUSTIFICADO = "Semana Justificada"

ACAO_CORRIGIR_NOME = "(1) Corrigir 'nome_entrada' no Cadastro"
ACAO_NAO_CADASTRADO = "(2) Pessoa Não Cadastrada (Verificar)"
ACAO_OK_IGNORADO = "OK (Ignorado)"
ACAO_OK_MATCH_CORRETO = "OK (Match Correto)"

ABA_ACOES_CADASTRO = "Acoes_de_Cadastro"
ABA_RESUMO_POR_ALUNO = "Resumo_por_Aluno"
ABA_REPORT_RAW = "report_raw"
ABA_KPI_GERAL = "kpi_geral_presenca"
ABA_PIVOT_TOTAL = "total_de_alunos_pivot"
ABA_PIVOT_ATINGIDOS = "atingidos_pivot"
ABA_PIVOT_PCT = "pct_atingimento_pivot"
ABA_XML_EXPORT = "export_XMLs"
ABA_RAW_PRESENCE = "raw_presence_data"
ABA_IGNORAR = "Pessoas para nao monitorar"